services:
  Speicher210\CloudinaryBundle\Factory\CloudinaryFactory:
    public: false
    arguments:
      - [ ]

  speicher210_cloudinary.cloudinary:
    class: Speicher210\CloudinaryBundle\Cloudinary\Cloudinary
    public: true
    factory: [ '@Speicher210\CloudinaryBundle\Factory\CloudinaryFactory', 'createCloudinary' ]

  Cloudinary\Cloudinary:
    alias: speicher210_cloudinary.cloudinary
    public: true

  Speicher210\CloudinaryBundle\Cloudinary\Uploader:
    class: Speicher210\CloudinaryBundle\Cloudinary\Uploader
    public: true
    factory: [ '@speicher210_cloudinary.cloudinary', 'uploadApi' ]

  speicher210_cloudinary.uploader:
    alias: Speicher210\CloudinaryBundle\Cloudinary\Uploader
    public: true

  Speicher210\CloudinaryBundle\Cloudinary\Admin:
    class: Speicher210\CloudinaryBundle\Cloudinary\Admin
    public: true
    factory: [ '@speicher210_cloudinary.cloudinary', 'adminApi' ]

  speicher210_cloudinary.admin:
    alias: Speicher210\CloudinaryBundle\Cloudinary\Admin
    public: true

  twig.extension.cloudinary:
    class: Speicher210\CloudinaryBundle\Twig\Extension\CloudinaryExtension
    public: true
    arguments:
      - '@speicher210_cloudinary.cloudinary'
    tags:
      - { name: 'twig.extension' }

  Speicher210\CloudinaryBundle\Command\DeleteCommand:
    arguments:
      - '@speicher210_cloudinary.admin'
    tags:
      - { name: 'console.command' }

  Speicher210\CloudinaryBundle\Command\InfoCommand:
    arguments:
      - '@speicher210_cloudinary.admin'
    tags:
      - { name: 'console.command' }

  Speicher210\CloudinaryBundle\Command\UploadCommand:
    arguments:
      - '@speicher210_cloudinary.uploader'
    tags:
      - { name: 'console.command' }

