variant = "loose"

[[issues]]
file = "src/Command/InfoCommand.php"
code = "psl-math-functions"
message = "Use the Psl math function instead of the PHP counterpart."
count = 2

[[issues]]
file = "src/Factory/CloudinaryFactory.php"
code = "no-isset"
message = "Use of the `isset` construct."
count = 1
