variant = "loose"

[[issues]]
file = "src/Command/DeleteCommand.php"
code = "invalid-array-index"
message = '''Invalid index type `string('deleted')` used for array access on `Cloudinary\Api\ApiResponse`.'''
count = 1

[[issues]]
file = "src/Command/DeleteCommand.php"
code = "invalid-iterator"
message = "The expression provided to `foreach` is not iterable. It resolved to type `mixed`, which is not iterable."
count = 1

[[issues]]
file = "src/Command/DeleteCommand.php"
code = "mixed-argument"
message = 'Invalid argument type for argument #1 of `Cloudinary\Api\Admin\AssetsTrait::deleteAssetsByPrefix`: expected `string`, but found `mixed`.'
count = 1

[[issues]]
file = "src/Command/DeleteCommand.php"
code = "mixed-argument"
message = 'Invalid argument type for argument #1 of `Cloudinary\Api\Admin\AssetsTrait::deleteAssets`: expected `array<array-key, mixed>|string`, but found `mixed`.'
count = 1

[[issues]]
file = "src/Command/DeleteCommand.php"
code = "mixed-argument"
message = 'Invalid argument type for argument #2 of `Psl\Str\format`: expected `float|int|string`, but found `mixed`.'
count = 2

[[issues]]
file = "src/Command/DeleteCommand.php"
code = "mixed-assignment"
message = "Assigning `mixed` type to a variable may lead to unexpected behavior."
count = 4

[[issues]]
file = "src/Command/InfoCommand.php"
code = "invalid-array-index"
message = "Invalid index type `int` used for array access on `string('kMGTPE')`."
count = 1

[[issues]]
file = "src/Command/InfoCommand.php"
code = "invalid-array-index"
message = '''Invalid index type `string('derived')` used for array access on `Cloudinary\Api\ApiResponse`.'''
count = 1

[[issues]]
file = "src/Command/InfoCommand.php"
code = "less-specific-nested-argument-type"
message = '''Argument type mismatch for argument #2 of `Speicher210\CloudinaryBundle\Command\InfoCommand::renderDerivedResources`: expected `array<array-key, array{'bytes': int, 'format': string, 'id': string, 'transformation': string, 'url': string}>`, but provided type `('V.arrayobject extends mixed)` is less specific.'''
count = 1

[[issues]]
file = "src/Command/InfoCommand.php"
code = "mixed-argument"
message = 'Invalid argument type for argument #1 of `Cloudinary\Api\Admin\AssetsTrait::asset`: expected `string`, but found `mixed`.'
count = 1

[[issues]]
file = "src/Command/InfoCommand.php"
code = "possibly-invalid-operand"
message = "Possibly invalid type for right operand."
count = 1

[[issues]]
file = "src/Command/UploadCommand.php"
code = "invalid-array-index"
message = '''Invalid index type `string('public_id')` used for array access on `Cloudinary\Api\ApiResponse`.'''
count = 2

[[issues]]
file = "src/Command/UploadCommand.php"
code = "mixed-argument"
message = 'Invalid argument type for argument #1 of `Symfony\Component\Finder\Finder::in`: expected `array<array-key, string>|string`, but found `mixed`.'
count = 1

[[issues]]
file = "src/Command/UploadCommand.php"
code = "mixed-argument"
message = 'Invalid argument type for argument #1 of `Symfony\Component\Finder\Finder::name`: expected `array<array-key, string>|string`, but found `mixed`.'
count = 1

[[issues]]
file = "src/Command/UploadCommand.php"
code = "possibly-invalid-argument"
message = 'Possible argument type mismatch for argument #1 of `Psl\Filesystem\get_filename`: expected `non-empty-string`, but possibly received `string`.'
count = 1
