name: "Continuous Integration"

on:
  push:
    branches: [ 1.x ]
  pull_request:
    branches: [ 1.x ]
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  check:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    env:
      SYMFONY_REQUIRE: ${{matrix.symfony_version}}
      SYMFONY_DEPRECATIONS_HELPER: "baselineFile=./tests/allowed-deprecations.json"
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - 8.3
          - 8.4
          - 8.5
        dependencies:
          - "highest"
        symfony_version:
          - ""
        include:
          # Test against latest Symfony 6.4
          - symfony_version: "6.4.*"
            php-version: "8.3"
            dependencies: "highest"
          - symfony_version: "6.4.*"
            php-version: "8.4"
            dependencies: "highest"
          - symfony_version: "6.4.*"
            php-version: "8.5"
            dependencies: "highest"

          # Test against latest Symfony 7.4
          - symfony_version: "7.4.*"
            php-version: "8.3"
            dependencies: "highest"
          - symfony_version: "7.4.*"
            php-version: "8.4"
            dependencies: "highest"
          - symfony_version: "7.4.*"
            php-version: "8.5"
            dependencies: "highest"

          # Test against the highest dependencies
          - php-version: "8.3"
            dependencies: "highest"
          - php-version: "8.4"
            dependencies: "highest"
          - php-version: "8.5"
            dependencies: "highest"

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          coverage: pcov
          tools: flex

      - name: "Configure Symfony version for symfony/flex"
        if: ${{ matrix.symfony_version }}
        run: composer config extra.symfony.require "${{ matrix.symfony_version }}.*"

      - name: "Install dependencies with Composer"
        uses: ramsey/composer-install@v4
        with:
          dependency-versions: "${{ matrix.dependencies }}"

      - name: Run checks
        run: |
          make check
